### ISSUE TITLE
Execution break in install.sh

### ISSUE THREAD

**Issue by quietsiren** [dfyvece/setup#1]
Script runs but breaks during Vundle Packages install.

[+] Installing dependencies
[+] Installing vim+tmux
[+] Installing pexpect
[*] Checking for Vundle
[*] Vundle already installed
[-] Installing Vundle PackagesTraceback (most recent call last):
  File "/tmp/tmp.x1Cfg6TZgl", line 5, in <module>
    vim.expect("Done!")
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fb3c2031450>
command: /usr/bin/vim
args: ['/usr/bin/vim']
buffer (last 100 chars): 'leInstall\r\x1b[97m\x1b[41mE492: Not an editor command: VundleInstall\x1b[m\x1b[20C0,0-1\x1b[9CAll\x1b[1;1H\x1b[?12l\x1b[?25h'
before (last 100 chars): 'leInstall\r\x1b[97m\x1b[41mE492: Not an editor command: VundleInstall\x1b[m\x1b[20C0,0-1\x1b[9CAll\x1b[1;1H\x1b[?12l\x1b[?25h'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9740
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("Done!")

**Comment by dfyvece** [comment]
Initial packages installation should take around 3 minutes, the module timed out after 30 seconds (this was a default setting I didn't know about). I removed the timeout setting so it shouldn't give that error anymore.
